# Generated by Django 5.2.1 on 2025-06-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_workout_delete_plan_delete_workoutsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
